### ISSUE TITLE
Predicting NMD function 

### ISSUE THREAD

**Issue by Drosofriends** [fursham-h/factR#5]
Hi, I'm using your tool for my analysis, when I use the function "predict NMD"  I obtain the table with  transcript, stop_to_lastEJ, num_of_downEJs,  `3'UTR_length` and  is_NMD.
For my analysis I want to determine the specific PTC position in my novel isoforms. 
Is it possible to implement another column in the output with the PTC position? Can I obtain this information  from the custom_GTF and NMD_object?
Thanks for the help.

**Comment by fursham-h** [comment]
Hi @Drosofriends. Thanks for using factR! That's actually a good point, I can add a new column with potential PTC coordinates together with the output of `predictNMD`. I'll work on it soon and update you.

**Comment by fursham-h** [comment]
Hi @Drosofriends. My apologies for taking this long, but we have made modifications to `predictNMD()` to output PTC coordinates as a separate column. Do test this out on your data and provide feedback on it :)

**Comment by fursham-h** [comment]
Closing this issue for now.
